solidity 0.7.6: Use "memory" instead of "calldata"
function is being called from an internal function which receives "memory" parameters. It uses those parameters as verifyStep() arguments and we were getting:
TypeError: Invalid type for argument in function call. Invalid implicit conversion from bytes memory to bytes calldata requested.