solidity 0.7.6: Use "storage" location instead of "memory"
Fixes:
TypeError: Type struct xxx is only valid in storage because it contains a (nested) mapping.